{maketoc}

!Purpose
This plugin allows sending notification to your [http://www.android.com/|Android] device.

It use the free [https://notifrier.appspot.com/|Notifry] application and you can download it from [https://market.android.com/details?id=com.notifry.android&amp;feature=search_result|Android Market].

Android and Android Market are [http://www.google.com/about/corporate/company/|Google]'s mark.

this service is free.
author of this plugin: Kriss@domogik.org
 

!Installation required
You need to install python-cjson package on your Domogik's server.
{CODE()}
easy_install python-cjson
{CODE}

!Application Installation required
{CODE()}
install the Notifry apps from Android Market to your Android device.
When install is finish, launch this app and register your account (a google account like gmail) and create your source (give the name you want).
{CODE}


!Plugin configuration
!!Enabling plugin
You can enable plugin by using :
{CODE()}
dmgenplug apushnot
{CODE}



You just have to reload administration page to see the plugin in the list.

!!Configuration
!!!startup-plugin
You can enable or disable the auto-start of the plugin.

!!!name
It is necessary to indicate an alias (what you want) for your 32 character key.

!!!source
It is necessary to indicate your 32 character key generated by Notifry's service.  

{img fileId=&quot;275&quot; thumb=&quot;y&quot; rel=&quot;box[g]&quot;}

You can create more alias with the &quot;add interface&quot; button.
Once the configuration is done, you can start the plugin (start button).

!Developper Notes

!!How the online plugin to test of order? 
In a final one, since the catalog xpl/bin it is necessary to launch the order. 
{CODE()}
./apushnot.py -f
{CODE}

In a final other, since the catalog xpl/bin it is necessary to launch the order. 
{CODE()}
./send.py xpl-cmnd sendmsg.push &quot;to=youralias,title=yourtitle,body=yourmessage&quot;
{CODE}

where youralias is the alias you have configure in the configuration page of the plugin
where yourtitle is the title of your message
where yourmessage is the message that must be transmitted


!!!XPL-CMND Structure
{CODE()}
sendmsg.push
{
to=&lt;Email address, User ID or Phone Number&gt;
title=&lt;titleof the message&gt; (optional)
body=&lt;Message body&gt;
signature=&lt;signature of the message&gt; (optional)
}
{CODE}

* [|sendmsg.push]


